# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVQvTklsZfLEqMSC1qnU_ExoPUxPzN8a
"""



import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt

df = pd.read_excel(
    r"C:\Users\Admin\Desktop\performance_dashboard\data\telugu_views.xlsx"
)


st.sidebar.title("Filters")

platform = st.sidebar.selectbox(
    "Select Platform",
    df["platform"].unique()
)

year = st.sidebar.multiselect(
    "Select Year",
    sorted(df["year"].unique()),
    default=sorted(df["year"].unique())
)

filtered_df = df[
    (df["platform"] == platform) &
    (df["year"].isin(year))
]

total_views = (
    filtered_df
    .groupby("channel", as_index=False)["no. of views"]
    .sum()
    .rename(columns={"no. of views": "total_views"})
)

avg_views = (
    filtered_df
    .groupby("channel", as_index=False)["no. of views"]
    .mean()
    .rename(columns={"no. of views": "avg_monthly_views"})
)

benchmark_df = total_views.merge(avg_views, on="channel")

benchmark_df["rank"] = benchmark_df["total_views"].rank(
    ascending=False, method="dense"
)

def performance_bucket(rank):
    if rank <= 3:
        return "Top Performer"
    elif rank <= 6:
        return "Mid Performer"
    else:
        return "Low Performer"

benchmark_df["performance_category"] = benchmark_df["rank"].apply(performance_bucket)

benchmark_df = benchmark_df.sort_values("rank")

st.title("📺 Aadhan Channel Performance Dashboard")

col1, col2, col3 = st.columns(3)

col1.metric("Total Channels", benchmark_df["channel"].nunique())
col2.metric("Total Views", int(benchmark_df["total_views"].sum()))
col3.metric("Top Channel", benchmark_df.iloc[0]["channel"])

st.subheader("📊 Channel Performance Benchmark")

st.dataframe(
    benchmark_df,
    width='stretch'
)

st.subheader("📈 Total Views by Channel")

fig, ax = plt.subplots(figsize=(10, 5))

bars = ax.bar(
    benchmark_df["channel"],
    benchmark_df["total_views"]
)

ax.set_xlabel("Channel")
ax.set_ylabel("Total Views")
ax.set_xticklabels(benchmark_df["channel"], rotation=45, ha="right")

# 🔹 ADD VALUES ON TOP OF BARS
for bar in bars:
    height = bar.get_height()
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f'{int(height):,}',   # comma-separated number
        ha='center',
        va='bottom',
        fontsize=9
    )

st.pyplot(fig)

